// <auto-generated />
using System;
using CDatos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CDatos.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared.Entities.Zombie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaInfeccion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NivelPeligro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Velocidad")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Zombie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Edad = 24,
                            Estado = "Vivo",
                            FechaInfeccion = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelPeligro = "Bajo",
                            Nombre = "Rickon",
                            Tipo = "Caminante",
                            Velocidad = 3.2000000000000002
                        },
                        new
                        {
                            Id = 2,
                            Edad = 30,
                            Estado = "Vivo",
                            FechaInfeccion = new DateTime(2024, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelPeligro = "Medio",
                            Nombre = "Luna",
                            Tipo = "Corredor",
                            Velocidad = 7.0999999999999996
                        },
                        new
                        {
                            Id = 3,
                            Edad = 45,
                            Estado = "Eliminado",
                            FechaInfeccion = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelPeligro = "Alto",
                            Nombre = "Brutus",
                            Tipo = "Mutante",
                            Velocidad = 2.5
                        },
                        new
                        {
                            Id = 4,
                            Edad = 27,
                            Estado = "Vivo",
                            FechaInfeccion = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelPeligro = "Medio",
                            Nombre = "Marla",
                            Tipo = "Caminante",
                            Velocidad = 4.0
                        },
                        new
                        {
                            Id = 5,
                            Edad = 51,
                            Estado = "Eliminado",
                            FechaInfeccion = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelPeligro = "Alto",
                            Nombre = "Gnasher",
                            Tipo = "Radioactivo",
                            Velocidad = 1.8
                        },
                        new
                        {
                            Id = 6,
                            Edad = 32,
                            Estado = "Vivo",
                            FechaInfeccion = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelPeligro = "Medio",
                            Nombre = "Corvus",
                            Tipo = "Corredor",
                            Velocidad = 8.0
                        },
                        new
                        {
                            Id = 7,
                            Edad = 19,
                            Estado = "Vivo",
                            FechaInfeccion = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelPeligro = "Bajo",
                            Nombre = "Elsa",
                            Tipo = "Caminante",
                            Velocidad = 2.8999999999999999
                        },
                        new
                        {
                            Id = 8,
                            Edad = 60,
                            Estado = "Eliminado",
                            FechaInfeccion = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelPeligro = "Alto",
                            Nombre = "Tor",
                            Tipo = "Mutante",
                            Velocidad = 2.0
                        },
                        new
                        {
                            Id = 9,
                            Edad = 34,
                            Estado = "Vivo",
                            FechaInfeccion = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelPeligro = "Medio",
                            Nombre = "Sable",
                            Tipo = "Corredor",
                            Velocidad = 6.2999999999999998
                        },
                        new
                        {
                            Id = 10,
                            Edad = 29,
                            Estado = "Vivo",
                            FechaInfeccion = new DateTime(2024, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelPeligro = "Bajo",
                            Nombre = "Vera",
                            Tipo = "Caminante",
                            Velocidad = 3.5
                        },
                        new
                        {
                            Id = 11,
                            Edad = 38,
                            Estado = "Eliminado",
                            FechaInfeccion = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelPeligro = "Alto",
                            Nombre = "Hawk",
                            Tipo = "Mutante",
                            Velocidad = 2.7999999999999998
                        },
                        new
                        {
                            Id = 12,
                            Edad = 25,
                            Estado = "Vivo",
                            FechaInfeccion = new DateTime(2024, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelPeligro = "Medio",
                            Nombre = "Dina",
                            Tipo = "Corredor",
                            Velocidad = 7.5
                        },
                        new
                        {
                            Id = 13,
                            Edad = 41,
                            Estado = "Eliminado",
                            FechaInfeccion = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelPeligro = "Alto",
                            Nombre = "Kragg",
                            Tipo = "Radioactivo",
                            Velocidad = 1.5
                        },
                        new
                        {
                            Id = 14,
                            Edad = 22,
                            Estado = "Vivo",
                            FechaInfeccion = new DateTime(2024, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelPeligro = "Bajo",
                            Nombre = "Milo",
                            Tipo = "Caminante",
                            Velocidad = 3.1000000000000001
                        },
                        new
                        {
                            Id = 15,
                            Edad = 35,
                            Estado = "Vivo",
                            FechaInfeccion = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelPeligro = "Medio",
                            Nombre = "Rosa",
                            Tipo = "Corredor",
                            Velocidad = 6.9000000000000004
                        },
                        new
                        {
                            Id = 16,
                            Edad = 50,
                            Estado = "Eliminado",
                            FechaInfeccion = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelPeligro = "Alto",
                            Nombre = "Xar",
                            Tipo = "Mutante",
                            Velocidad = 2.2999999999999998
                        },
                        new
                        {
                            Id = 17,
                            Edad = 31,
                            Estado = "Vivo",
                            FechaInfeccion = new DateTime(2024, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelPeligro = "Medio",
                            Nombre = "Ivy",
                            Tipo = "Caminante",
                            Velocidad = 4.2000000000000002
                        },
                        new
                        {
                            Id = 18,
                            Edad = 40,
                            Estado = "Eliminado",
                            FechaInfeccion = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelPeligro = "Alto",
                            Nombre = "Nox",
                            Tipo = "Radioactivo",
                            Velocidad = 1.8999999999999999
                        },
                        new
                        {
                            Id = 19,
                            Edad = 28,
                            Estado = "Vivo",
                            FechaInfeccion = new DateTime(2024, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelPeligro = "Bajo",
                            Nombre = "Kira",
                            Tipo = "Corredor",
                            Velocidad = 5.7999999999999998
                        },
                        new
                        {
                            Id = 20,
                            Edad = 36,
                            Estado = "Eliminado",
                            FechaInfeccion = new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NivelPeligro = "Alto",
                            Nombre = "Omen",
                            Tipo = "Mutante",
                            Velocidad = 2.6000000000000001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
